version: "3.8"
services:
  discovery-service:
    build:
      context: ./discovery-service
    container_name: "discovery-service"
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  gateway-service:
    build:
      context: ./gateway-service
    container_name: "gateway-service"
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - SERVER_PORT=8888
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka/
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  customer-service:
    build:
      context: ./customer-service
    container_name: "customer-service"
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - SERVER_PORT=9091
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka/
    ports:
      - "9091:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  account-service:
    build:
      context: ./account-service
    container_name: "account-service"
    depends_on:
      customer-service:
        condition: service_healthy
    environment:
      - SERVER_PORT=9092
      - EUREKA_SERVER_URL=http://discovery-service:8761/eureka/
    ports:
      - "9092:9092"

  angular-client:
    build:
      context: ./angular-client
    container_name: angular-client
    depends_on:
      discovery-service:
        condition: service_healthy
    ports:
      - "4200:80" # Map host port 4200 to container's default nginx port 80
