version: "3.8"
services:
  customer-service:
    build:
      context: ./customer-service
    container_name: "customer-service"
    environment:
      - SERVER_PORT=9091
    ports:
      - "9091:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  account-service:
    build:
      context: ./account-service
    container_name: "account-service"
    depends_on:
      customer-service:
        condition: service_healthy
    environment:
      - SERVER_PORT=9092
    ports:
      - "9092:9092"