apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: zacklordbing1909/account-service:latest
          ports:
            - containerPort: 9092
          env:
            - name: SERVER_PORT
              value: "9092"
            - name: EUREKA_SERVER_URL
              value: "http://discovery-service.cicd.svc.cluster.local:8761/eureka/"
            - name: CONFIG_SERVER_URL
              value: "http://config-service.cicd.svc.cluster.local:9999/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgres://account-postgres.cicd.svc.cluster.local:5432/account-db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgrespassword"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9092
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: cicd
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP
