apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-postgres
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-postgres
  template:
    metadata:
      labels:
        app: account-postgres
    spec:
      containers:
      - name: account-postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "postgrespassword"
        - name: POSTGRES_DB
          value: "account-db"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgres/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: account-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: account-postgres
  namespace: cicd
spec:
  selector:
    app: account-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-postgres-pvc
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: account-postgres-pv
  namespace: cicd
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/account-postgres
