apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-client
  labels:
    app: angular-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-client
  template:
    metadata:
      labels:
        app: angular-client
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: wait-for-gateway-service
          image: busybox
          command: ['sh', '-c', 'until nc -z gateway-service.cicd.svc.cluster.local 8888; do echo waiting for gateway-service; sleep 5; done;']
      containers:
      - name: angular-service
        image: docker.io/zacklordbing1909/angular-client:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: angular-client
  labels:
    app: angular-client
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: angular-client
