apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-client
  labels:
    app: angular-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-client
  template:
    metadata:
      labels:
        app: angular-client
    spec:
      containers:
      - name: angular-client
        image: zacklordbing1909/angular-client:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-client
  labels:
    app: angular-client
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: angular-client
