apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: docker.io/zacklordbing1909/config-service:latest
          ports:
            - containerPort: 9999
          env:
            - name: SERVER_PORT
              value: "9999"
            - name: EUREKA_SERVER_URL
              value: "http://discovery-service.cicd.svc.cluster.local:8761/eureka"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: cicd
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: ClusterIP
