apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      initContainers:
        - name: wait-for-config-service
          image: busybox
          command: ['sh', '-c', 'until nc -z config-service.cicd.svc.cluster.local 9999; do echo waiting for config-service; sleep 5; done;']
        - name: wait-for-customer-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z customer-mysql.cicd.svc.cluster.local 3306; do echo waiting for customer-mysql; sleep 5; done;']
      containers:
        - name: customer-service
          image: docker.io/zacklordbing1909/customer-service:latest
          ports:
            - containerPort: 9091
          env:
            - name: SERVER_PORT
              value: "9091"
            - name: EUREKA_SERVER_URL
              value: "http://discovery-service.cicd.svc.cluster.local:8761/eureka/"
            - name: CONFIG_SERVER_URL
              value: "http://config-service.cicd.svc.cluster.local:9999/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://customer-mysql.cicd.svc.cluster.local:3306/customer-db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "rootpassword"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9091
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9091
            initialDelaySeconds: 10
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: cicd
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP
