apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: discovery-service
          image: docker.io/zacklordbing1909/discovery-service:latest
          ports:
            - containerPort: 8761
          env:
            - name: SERVER_PORT
              value: "8761"
            - name: JAVA_OPTS
              value: "-Xmx712m -Xms512m -Dlogging.level.root=INFO"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 900  # Increased from 600 to 900
            periodSeconds: 30
            timeoutSeconds: 20       # Increased from 10 to 20
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 1200  # Increased from 900 to 1200
            periodSeconds: 30         # Less frequent checks
            timeoutSeconds: 20         # Increased from 10 to 20
            failureThreshold: 5       # More failures allowed before restart
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: cicd
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
