apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: docker.io/zacklordbing1909/discovery-service:latest
          ports:
            - containerPort: 8761
          env:
            - name: SERVER_PORT
              value: "8761"
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m -Dlogging.level.root=INFO"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "768Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 180  # Much longer than readiness probe
            periodSeconds: 30         # Less frequent checks
            timeoutSeconds: 10
            failureThreshold: 5       # More failures allowed before restart
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: cicd
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
