apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: zacklordbing1909/gateway-service:latest
          ports:
            - containerPort: 8888
          env:
            - name: SERVER_PORT
              value: "8888"
            - name: EUREKA_SERVER_URL
              value: "http://discovery-service.cicd.svc.cluster.local:8761/eureka/"
            - name: CONFIG_SERVER_URL
              value: "http://config-service.cicd.svc.cluster.local:9999/"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: cicd
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
