spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081
          predicates:
            - Path=/api/customers/**
        - id: r2
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**
  application:
    name: gateway-service
server:
  port: 8888